# Server Configuration
listen_addr: "0.0.0.0"
listen_port: 51820
private_key_file: "configs/server.key"
tunnel_ip: "10.0.0.1/24"

# A list of authorized clients.
# The server will only allow connections from clients whose public keys are listed here.
clients:
  - public_key_file: "configs/client.pub"
    tunnel_ip: "10.0.0.2"
